### ISSUE TITLE
请问你的wapper 包装类在哪里呢？

### ISSUE THREAD

**Issue by rebysfu** [Json-Lin/spring-boot-practice#1]
你这种方式是适合使用jdbcTemple的方式进行多数据源事务管理

**Comment by Json-Lin** [comment]
你说的是AtomikosXADataSourceWrapper?这个是系统的包装类，原理是要返回一个AtomikosDataSourceBean 。我们是手动注入数据源的在InitDruidDataSource(druidXADataSource, dataSourceProperties);下面的那些代码，实现的就是跟包装类相同的功能。
事务的话jdbc或者hibernate都可以，只不过hibernate你不仅仅需要配置多个数据源，还需要配置多个sessionFactory

**Comment by rebysfu** [comment]
嗯。最近也在做这块的demo ,orm 采用的是mybaits. 非常感谢你的回答

**Comment by Json-Lin** [comment]
over
